### ISSUE TITLE
NOT RESPONDING

### ISSUE THREAD

**Issue by iarsslen** [Snowl/Poro#1]
I can't even login it says logging on but the server won't respond to the LOL client (after accepting the certificate).
Any help pls

**Comment by snowl** [comment]
This is still very experimental!!!! If you could give me the line that it exceptions on that would be handy. It needs a website and I haven't included it yet so that may be why it fails...

**Comment by iarsslen** [comment]
it was an end of stream exception before i download ur latest update but now it just go fine but the client doesn't connect.
USING OCE SERVER

**Comment by snowl** [comment]
what does the console say

**Comment by iarsslen** [comment]
The Console just show the 2 first lines and [LOG] patcher detected.....
I think my problem is probably with the SSL Handshake. did u modify any LoL file or something to force ssl authentification process ?

THIS RESPONSE DATA WAS DEBUG'D from Line 41 AuthServer.cs (response)
 {"rate":75,"reason":"login_rate","status":"LOGIN","lqt":{"other":"","fingerprint":"","signature":"","timestamp":1418934199554,"uuid":"","resources":"lol","account_id":200006292,"account_name":"snowl"},"delay":10000,"inGameCredentials":{"inGame":false,"summonerId":null,"serverIp":null,"serverPort":null,"encryptionKey":null,"handshakeToken":null},"user":"snowl"}  after this command it says logging on but after a while LoL client closes the connection.  The server stays online and can handle another login process with no problem.

**Comment by iarsslen** [comment]
Problem Solved by matching the IP address in the CERTIFICATE AND LOCAL IP of the SERVER.
